# Generated by Django 3.2.6 on 2021-08-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incidentnumber', models.AutoField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('job_role', models.CharField(max_length=30)),
                ('incident_type', models.CharField(max_length=20)),
                ('siteID', models.CharField(max_length=6)),
                ('site_name', models.CharField(max_length=50)),
                ('incident_date', models.DateTimeField()),
                ('incident_time', models.TimeField()),
                ('files', models.FileField(max_length=20, upload_to='')),
                ('person_involved', models.CharField(max_length=220)),
                ('incident_description', models.CharField(max_length=220)),
                ('witness', models.CharField(max_length=220)),
                ('loss', models.CharField(max_length=220)),
                ('reported_to', models.CharField(max_length=80)),
                ('date_reported', models.DateTimeField()),
                ('report_method', models.CharField(max_length=20)),
                ('actions', models.CharField(max_length=220)),
            ],
        ),
    ]
