# Generated by Django 3.2.5 on 2021-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMRegister', '0005_auto_20210810_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_description',
            field=models.CharField(max_length=2220, verbose_name='Incident Description (Full Details)'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('Operations', 'Operations'), ('OHSE', 'OHSE'), ('Admin', 'Admin'), ('IT', 'IT'), ('Security', 'Security')], max_length=200, verbose_name='Incident Type'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='report_method',
            field=models.CharField(blank=True, choices=[('Text Messages', 'Text Messages'), ('Phone Call', 'Phone Call'), ('Email', 'Email'), ('This form', 'This form')], max_length=20, null=True, verbose_name='Report Method'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_to',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Reported to:'),
        ),
    ]
