# Generated by Django 3.2.3 on 2021-08-12 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0002_auto_20210812_1357'),
        ('IMRegister', '0006_auto_20210810_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='manager',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.DO_NOTHING, to='Managers.managermodel', verbose_name='Manager'),
            preserve_default=False,
        ),
    ]
