# Generated by Django 3.2.3 on 2021-08-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0003_alter_managermodel_options'),
        ('IMRegister', '0007_incident_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='imme_action2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Immediate action taken'),
        ),
        migrations.AddField(
            model_name='incident',
            name='imme_action2_when',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When'),
        ),
        migrations.AddField(
            model_name='incident',
            name='imme_action2_whom',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='By whom'),
        ),
        migrations.AddField(
            model_name='incident',
            name='long_action2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Long term action taken'),
        ),
        migrations.AddField(
            model_name='incident',
            name='long_action2_when',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When'),
        ),
        migrations.AddField(
            model_name='incident',
            name='long_action2_whom',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='By whom'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='manager',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.DO_NOTHING, to='Managers.managermodel', verbose_name='Manager'),
        ),
    ]
