# Generated by Django 3.2.7 on 2021-11-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMRegister', '0010_rename_siteid_incident_siteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='direct_cause',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Direct Cause of Incident'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Attach Pictures'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='imme_action',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Immediate action taken'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='imme_action2',
            field=models.CharField(blank=True, max_length=2200, null=True, verbose_name='Second Immediate action taken'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_area_detail',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Incident Area description'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='long_action2',
            field=models.CharField(blank=True, max_length=2600, null=True, verbose_name='Second Long term action taken'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='root_cause',
            field=models.CharField(blank=True, max_length=1400, null=True, verbose_name='Root Cause of Incident'),
        ),
    ]
