# Generated by Django 3.2.7 on 2021-11-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMRegister', '0011_auto_20211118_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Attach Pictures'),
        ),
    ]
