# Generated by Django 3.2.7 on 2021-11-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMRegister', '0013_auto_20211124_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='Uploads', verbose_name='Attach Pictures'),
        ),
    ]
