# Generated by Django 3.2.7 on 2021-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMRegister', '0014_alter_incident_file1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Attach Pictures'),
        ),
    ]
