# Generated by Django 3.2.7 on 2021-12-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMRegister', '0015_alter_incident_file1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='file1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Attach Pictures'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='file2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Attach Pictures'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='file3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Attach Pictures'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='file4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Attach Pictures'),
        ),
    ]
