# Generated by Django 3.2.3 on 2021-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managermodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='managermodel',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
