# Generated by Django 3.2.6 on 2021-08-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incidentnumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
