# Generated by Django 3.2.3 on 2021-08-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMRegister', '0008_auto_20210817_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='imme_action2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Second Immediate action taken'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='long_action2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Second Long term action taken'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='siteID',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Site ID'),
        ),
    ]
