# Generated by Django 3.2.6 on 2021-08-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMRegister', '0002_alter_incident_incidentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='actions',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='job_role',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='incident',
            name='loss',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='siteID',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='witness',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
