# Generated by Django 3.2.5 on 2021-08-09 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IMRegister', '0003_auto_20210803_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='actions',
            new_name='lessons',
        ),
        migrations.AddField(
            model_name='incident',
            name='direct_cause',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='imme_action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='imme_action_when',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='imme_action_whom',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_area_detail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='long_action',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='long_action_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='long_action_whom',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='lost_hr',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='root_cause',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
